snapshot of project "ded", label t20221231

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 # From configure.in Revision: 12.10 .
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20221009.
+# Generated by Autoconf 2.52.20221202.
 #
 # Copyright 2003-2021,2022	Thomas E. Dickey
 # Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -728,7 +728,7 @@ This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
 It was created by $as_me, which was
-generated by GNU Autoconf 2.52.20221009.  Invocation command line was
+generated by GNU Autoconf 2.52.20221202.  Invocation command line was
 
   $ $0 $@
 
@@ -3266,12 +3266,15 @@ done
 			fi
 		done
 	else
-		cf_libdir=`echo "$cf_libdir" | sed -e 's,/lib[^/]*$,share,'`
+		cf_libdir=`echo "$cf_libdir" | sed -e 's,/td_lib.mk,,' -e 's,/lib[^/]*,/share,'`
 		if test -f "$cf_libdir/td_lib.mk" ; then
+			cf_td_lib_rules=yes
+		elif test -f "$cf_libdir/td/td_lib.mk" ; then
+			cf_libdir="$cf_libdir/td"
 			cf_td_lib_rules=yes
 		fi
 	fi
-	test $cf_td_lib_rules = no && { { echo "$as_me:3274: error: Cannot find td_lib.mk" >&5
+	test "$cf_td_lib_rules" = yes || { { echo "$as_me:3277: error: Cannot find td_lib.mk" >&5
 echo "$as_me: error: Cannot find td_lib.mk" >&2;}
    { (exit 1); exit 1; }; }
 	TD_LIB_rules=$cf_libdir
@@ -3281,7 +3284,7 @@ else
 	TD_LIB_rules=$cf_cv_tdlib_devel/support
 fi
 
-echo "$as_me:3284: checking if ${MAKE:-make} program knows about archives" >&5
+echo "$as_me:3287: checking if ${MAKE:-make} program knows about archives" >&5
 echo $ECHO_N "checking if ${MAKE:-make} program knows about archives... $ECHO_C" >&6
 if test "${cf_cv_ar_rules+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3347,7 +3350,7 @@ CF_EOF
 	then
 		cf_cv_ar_rules=no
 	else
-		{ { echo "$as_me:3350: error: I do not know how to construct a library" >&5
+		{ { echo "$as_me:3353: error: I do not know how to construct a library" >&5
 echo "$as_me: error: I do not know how to construct a library" >&2;}
    { (exit 1); exit 1; }; }
 	fi
@@ -3356,10 +3359,10 @@ rm -rf "$cf_dir"
 
 fi
 
-echo "$as_me:3359: result: $cf_cv_ar_rules" >&5
+echo "$as_me:3362: result: $cf_cv_ar_rules" >&5
 echo "${ECHO_T}$cf_cv_ar_rules" >&6
 
-echo "$as_me:3362: checking for style of include in makefiles" >&5
+echo "$as_me:3365: checking for style of include in makefiles" >&5
 echo $ECHO_N "checking for style of include in makefiles... $ECHO_C" >&6
 
 make_include_left=""
@@ -3399,7 +3402,7 @@ done
 rm -rf $cf_inc $cf_dir
 
 if test -z "$make_include_left" ; then
-	{ { echo "$as_me:3402: error: Your $ac_make program does not support includes" >&5
+	{ { echo "$as_me:3405: error: Your $ac_make program does not support includes" >&5
 echo "$as_me: error: Your $ac_make program does not support includes" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -3408,12 +3411,12 @@ if test ".$make_include_quote" != .unknown ; then
 	make_include_right="$make_include_quote"
 fi
 
-echo "$as_me:3411: result: ${make_include_left}file${make_include_right}" >&5
+echo "$as_me:3414: result: ${make_include_left}file${make_include_right}" >&5
 echo "${ECHO_T}${make_include_left}file${make_include_right}" >&6
 
 ### Compiler characteristics
 
-echo "$as_me:3416: checking for fgrep" >&5
+echo "$as_me:3419: checking for fgrep" >&5
 echo $ECHO_N "checking for fgrep... $ECHO_C" >&6
 if test "${ac_cv_path_FGREP+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3425,7 +3428,7 @@ else
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:3428: checking for $ac_word" >&5
+echo "$as_me:3431: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_FGREP+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -3442,7 +3445,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_FGREP="$ac_dir/$ac_word"
-   echo "$as_me:3445: found $ac_dir/$ac_word" >&5
+   echo "$as_me:3448: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -3453,10 +3456,10 @@ fi
 FGREP=$ac_cv_path_FGREP
 
 if test -n "$FGREP"; then
-  echo "$as_me:3456: result: $FGREP" >&5
+  echo "$as_me:3459: result: $FGREP" >&5
 echo "${ECHO_T}$FGREP" >&6
 else
-  echo "$as_me:3459: result: no" >&5
+  echo "$as_me:3462: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -3464,16 +3467,16 @@ fi
 done
 test -n "$FGREP" || FGREP=": "
 
-     test "x$ac_cv_path_FGREP" = "x:" && { { echo "$as_me:3467: error: cannot find workable fgrep" >&5
+     test "x$ac_cv_path_FGREP" = "x:" && { { echo "$as_me:3470: error: cannot find workable fgrep" >&5
 echo "$as_me: error: cannot find workable fgrep" >&2;}
    { (exit 1); exit 1; }; }
    fi
 fi
-echo "$as_me:3472: result: $ac_cv_path_FGREP" >&5
+echo "$as_me:3475: result: $ac_cv_path_FGREP" >&5
 echo "${ECHO_T}$ac_cv_path_FGREP" >&6
  FGREP="$ac_cv_path_FGREP"
 
-echo "$as_me:3476: checking if you want to use C11 _Noreturn feature" >&5
+echo "$as_me:3479: checking if you want to use C11 _Noreturn feature" >&5
 echo $ECHO_N "checking if you want to use C11 _Noreturn feature... $ECHO_C" >&6
 
 # Check whether --enable-stdnoreturn or --disable-stdnoreturn was given.
@@ -3490,17 +3493,17 @@ else
 	enable_stdnoreturn=no
 
 fi;
-echo "$as_me:3493: result: $enable_stdnoreturn" >&5
+echo "$as_me:3496: result: $enable_stdnoreturn" >&5
 echo "${ECHO_T}$enable_stdnoreturn" >&6
 
 if test $enable_stdnoreturn = yes; then
-echo "$as_me:3497: checking for C11 _Noreturn feature" >&5
+echo "$as_me:3500: checking for C11 _Noreturn feature" >&5
 echo $ECHO_N "checking for C11 _Noreturn feature... $ECHO_C" >&6
 if test "${cf_cv_c11_noreturn+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >"conftest.$ac_ext" <<_ACEOF
-#line 3503 "configure"
+#line 3506 "configure"
 #include "confdefs.h"
 
 #include <stdio.h>
@@ -3517,16 +3520,16 @@ if (feof(stdin)) giveup()
 }
 _ACEOF
 rm -f "conftest.$ac_objext"
-if { (eval echo "$as_me:3520: \"$ac_compile\"") >&5
+if { (eval echo "$as_me:3523: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3523: \$? = $ac_status" >&5
+  echo "$as_me:3526: \$? = $ac_status" >&5
   (exit "$ac_status"); } &&
          { ac_try='test -s "conftest.$ac_objext"'
-  { (eval echo "$as_me:3526: \"$ac_try\"") >&5
+  { (eval echo "$as_me:3529: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:3529: \$? = $ac_status" >&5
+  echo "$as_me:3532: \$? = $ac_status" >&5
   (exit "$ac_status"); }; }; then
   cf_cv_c11_noreturn=yes
 else
@@ -3537,7 +3540,7 @@ fi
 rm -f "conftest.$ac_objext" "conftest.$ac_ext"
 
 fi
-echo "$as_me:3540: result: $cf_cv_c11_noreturn" >&5
+echo "$as_me:3543: result: $cf_cv_c11_noreturn" >&5
 echo "${ECHO_T}$cf_cv_c11_noreturn" >&6
 else
 	cf_cv_c11_noreturn=no,
@@ -3593,16 +3596,16 @@ then
 		then
 			test -n "$verbose" && echo "	repairing CFLAGS: $CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3596: testing repairing CFLAGS: $CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3599: testing repairing CFLAGS: $CFLAGS ..." 1>&5
 
 			CFLAGS="$cf_temp_flags"
 			test -n "$verbose" && echo "	... fixed $CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3601: testing ... fixed $CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3604: testing ... fixed $CFLAGS ..." 1>&5
 
 			test -n "$verbose" && echo "	... extra $EXTRA_CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3605: testing ... extra $EXTRA_CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3608: testing ... extra $EXTRA_CFLAGS ..." 1>&5
 
 		fi
 		;;
@@ -3641,16 +3644,16 @@ then
 		then
 			test -n "$verbose" && echo "	repairing CPPFLAGS: $CPPFLAGS" 1>&6
 
-echo "${as_me:-configure}:3644: testing repairing CPPFLAGS: $CPPFLAGS ..." 1>&5
+echo "${as_me:-configure}:3647: testing repairing CPPFLAGS: $CPPFLAGS ..." 1>&5
 
 			CPPFLAGS="$cf_temp_flags"
 			test -n "$verbose" && echo "	... fixed $CPPFLAGS" 1>&6
 
-echo "${as_me:-configure}:3649: testing ... fixed $CPPFLAGS ..." 1>&5
+echo "${as_me:-configure}:3652: testing ... fixed $CPPFLAGS ..." 1>&5
 
 			test -n "$verbose" && echo "	... extra $EXTRA_CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3653: testing ... extra $EXTRA_CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3656: testing ... extra $EXTRA_CFLAGS ..." 1>&5
 
 		fi
 		;;
@@ -3689,23 +3692,23 @@ then
 		then
 			test -n "$verbose" && echo "	repairing LDFLAGS: $LDFLAGS" 1>&6
 
-echo "${as_me:-configure}:3692: testing repairing LDFLAGS: $LDFLAGS ..." 1>&5
+echo "${as_me:-configure}:3695: testing repairing LDFLAGS: $LDFLAGS ..." 1>&5
 
 			LDFLAGS="$cf_temp_flags"
 			test -n "$verbose" && echo "	... fixed $LDFLAGS" 1>&6
 
-echo "${as_me:-configure}:3697: testing ... fixed $LDFLAGS ..." 1>&5
+echo "${as_me:-configure}:3700: testing ... fixed $LDFLAGS ..." 1>&5
 
 			test -n "$verbose" && echo "	... extra $EXTRA_CFLAGS" 1>&6
 
-echo "${as_me:-configure}:3701: testing ... extra $EXTRA_CFLAGS ..." 1>&5
+echo "${as_me:-configure}:3704: testing ... extra $EXTRA_CFLAGS ..." 1>&5
 
 		fi
 		;;
 	esac
 fi
 
-echo "$as_me:3708: checking if you want to turn on gcc warnings" >&5
+echo "$as_me:3711: checking if you want to turn on gcc warnings" >&5
 echo $ECHO_N "checking if you want to turn on gcc warnings... $ECHO_C" >&6
 
 # Check whether --enable-warnings or --disable-warnings was given.
@@ -3722,7 +3725,7 @@ else
 	enable_warnings=no
 
 fi;
-echo "$as_me:3725: result: $enable_warnings" >&5
+echo "$as_me:3728: result: $enable_warnings" >&5
 echo "${ECHO_T}$enable_warnings" >&6
 if test "$enable_warnings" = "yes"
 then
@@ -3745,10 +3748,11 @@ cat > conftest.i <<EOF
 EOF
 if test "$GCC" = yes
 then
-	{ echo "$as_me:3748: checking for $CC __attribute__ directives..." >&5
+	{ echo "$as_me:3751: checking for $CC __attribute__ directives..." >&5
 echo "$as_me: checking for $CC __attribute__ directives..." >&6;}
 cat > "conftest.$ac_ext" <<EOF
-#line 3751 "${as_me:-configure}"
+#line 3754 "${as_me:-configure}"
+#include <stdio.h>
 #include "confdefs.h"
 #include "conftest.h"
 #include "conftest.i"
@@ -3797,12 +3801,12 @@ EOF
 			;;
 		esac
 
-		if { (eval echo "$as_me:3800: \"$ac_compile\"") >&5
+		if { (eval echo "$as_me:3804: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3803: \$? = $ac_status" >&5
+  echo "$as_me:3807: \$? = $ac_status" >&5
   (exit "$ac_status"); }; then
-			test -n "$verbose" && echo "$as_me:3805: result: ... $cf_attribute" >&5
+			test -n "$verbose" && echo "$as_me:3809: result: ... $cf_attribute" >&5
 echo "${ECHO_T}... $cf_attribute" >&6
 			cat conftest.h >>confdefs.h
 			case "$cf_attribute" in
@@ -3863,7 +3867,7 @@ fi
 
 if test "x$have_x" = xyes; then echo "skipping X-const check"; fi
 cat > "conftest.$ac_ext" <<EOF
-#line 3866 "${as_me:-configure}"
+#line 3870 "${as_me:-configure}"
 int main(int argc, char *argv[]) { return (argv[argc-1] == 0) ; }
 EOF
 if test "$INTEL_COMPILER" = yes
@@ -3879,7 +3883,7 @@ then
 # remark #981: operands are evaluated in unspecified order
 # warning #279: controlling expression is constant
 
-	{ echo "$as_me:3882: checking for $CC warning options..." >&5
+	{ echo "$as_me:3886: checking for $CC warning options..." >&5
 echo "$as_me: checking for $CC warning options..." >&6;}
 	cf_save_CFLAGS="$CFLAGS"
 	EXTRA_CFLAGS="$EXTRA_CFLAGS -Wall"
@@ -3895,12 +3899,12 @@ echo "$as_me: checking for $CC warning options..." >&6;}
 		wd981
 	do
 		CFLAGS="$cf_save_CFLAGS $EXTRA_CFLAGS -$cf_opt"
-		if { (eval echo "$as_me:3898: \"$ac_compile\"") >&5
+		if { (eval echo "$as_me:3902: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3901: \$? = $ac_status" >&5
+  echo "$as_me:3905: \$? = $ac_status" >&5
   (exit "$ac_status"); }; then
-			test -n "$verbose" && echo "$as_me:3903: result: ... -$cf_opt" >&5
+			test -n "$verbose" && echo "$as_me:3907: result: ... -$cf_opt" >&5
 echo "${ECHO_T}... -$cf_opt" >&6
 			EXTRA_CFLAGS="$EXTRA_CFLAGS -$cf_opt"
 		fi
@@ -3908,7 +3912,7 @@ echo "${ECHO_T}... -$cf_opt" >&6
 	CFLAGS="$cf_save_CFLAGS"
 elif test "$GCC" = yes && test "$GCC_VERSION" != "unknown"
 then
-	{ echo "$as_me:3911: checking for $CC warning options..." >&5
+	{ echo "$as_me:3915: checking for $CC warning options..." >&5
 echo "$as_me: checking for $CC warning options..." >&6;}
 	cf_save_CFLAGS="$CFLAGS"
 	cf_warn_CONST=""
@@ -3931,12 +3935,12 @@ echo "$as_me: checking for $CC warning options..." >&6;}
 		Wundef Wno-inline $cf_gcc_warnings $cf_warn_CONST
 	do
 		CFLAGS="$cf_save_CFLAGS $EXTRA_CFLAGS -$cf_opt"
-		if { (eval echo "$as_me:3934: \"$ac_compile\"") >&5
+		if { (eval echo "$as_me:3938: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
-  echo "$as_me:3937: \$? = $ac_status" >&5
+  echo "$as_me:3941: \$? = $ac_status" >&5
   (exit "$ac_status"); }; then
-			test -n "$verbose" && echo "$as_me:3939: result: ... -$cf_opt" >&5
+			test -n "$verbose" && echo "$as_me:3943: result: ... -$cf_opt" >&5
 echo "${ECHO_T}... -$cf_opt" >&6
 			case "$cf_opt" in
 			(Winline)
@@ -3944,7 +3948,7 @@ echo "${ECHO_T}... -$cf_opt" >&6
 				([34].*)
 					test -n "$verbose" && echo "	feature is broken in gcc $GCC_VERSION" 1>&6
 
-echo "${as_me:-configure}:3947: testing feature is broken in gcc $GCC_VERSION ..." 1>&5
+echo "${as_me:-configure}:3951: testing feature is broken in gcc $GCC_VERSION ..." 1>&5
 
 					continue;;
 				esac
@@ -3954,7 +3958,7 @@ echo "${as_me:-configure}:3947: testing feature is broken in gcc $GCC_VERSION ..
 				([12].*)
 					test -n "$verbose" && echo "	feature is broken in gcc $GCC_VERSION" 1>&6
 
-echo "${as_me:-configure}:3957: testing feature is broken in gcc $GCC_VERSION ..." 1>&5
+echo "${as_me:-configure}:3961: testing feature is broken in gcc $GCC_VERSION ..." 1>&5
 
 					continue;;
 				esac
@@ -4090,7 +4094,7 @@ rm -f confdef2opt.sed
 : "${CONFIG_STATUS=./config.status}"
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:4093: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:4097: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >"$CONFIG_STATUS" <<_ACEOF
 #! $SHELL
@@ -4221,7 +4225,7 @@ EOF
 cat >>"$CONFIG_STATUS" <<EOF
 ac_cs_version="\\
 config.status
-configured by $0, generated by GNU Autoconf 2.52.20221009,
+configured by $0, generated by GNU Autoconf 2.52.20221202,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 2003-2021,2022	Thomas E. Dickey
@@ -4266,7 +4270,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4269: error: ambiguous option: $1
+    { { echo "$as_me:4273: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4285,7 +4289,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:4288: error: unrecognized option: $1
+  -*) { { echo "$as_me:4292: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4304,7 +4308,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me 2.52.20221009, executed with
+This file was extended by $as_me 2.52.20221202, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -4337,7 +4341,7 @@ do
   "test/makefile" ) CONFIG_FILES="$CONFIG_FILES test/makefile" ;;
   "user/makefile" ) CONFIG_FILES="$CONFIG_FILES user/makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
-  *) { { echo "$as_me:4340: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4344: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4593,7 +4597,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4596: creating $ac_file" >&5
+    { echo "$as_me:4600: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4611,7 +4615,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo "$tmp"/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4614: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4618: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo "$f";;
@@ -4624,7 +4628,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo "$srcdir/$f"
          else
            # /dev/null tree
-           { { echo "$as_me:4627: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4631: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4640,7 +4644,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
       if test -n "$ac_seen"; then
         ac_used=`grep '@datarootdir@' "$ac_item"`
         if test -z "$ac_used"; then
-          { echo "$as_me:4643: WARNING: datarootdir was used implicitly but not set:
+          { echo "$as_me:4647: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used implicitly but not set:
 $ac_seen" >&2;}
@@ -4649,7 +4653,7 @@ $ac_seen" >&2;}
       fi
       ac_seen=`grep '${datarootdir}' "$ac_item"`
       if test -n "$ac_seen"; then
-        { echo "$as_me:4652: WARNING: datarootdir was used explicitly but not set:
+        { echo "$as_me:4656: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: datarootdir was used explicitly but not set:
 $ac_seen" >&2;}
@@ -4694,7 +4698,7 @@ cat >>"$CONFIG_STATUS" <<\EOF
             ac_init=`$EGREP '[ 	]*'$ac_name'[ 	]*=' "$ac_file"`
             if test -z "$ac_init"; then
               ac_seen=`echo "$ac_seen" |sed -e 's,^,'"$ac_file"':,'`
-              { echo "$as_me:4697: WARNING: Variable $ac_name is used but was not set:
+              { echo "$as_me:4701: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&5
 echo "$as_me: WARNING: Variable $ac_name is used but was not set:
 $ac_seen" >&2;}
@@ -4705,7 +4709,7 @@ $ac_seen" >&2;}
     $EGREP -n '@[A-Z_][A-Z_0-9]+@' "$ac_file" >>"$tmp"/out
     if test -s "$tmp"/out; then
       ac_seen=`sed -e 's,^,'"$ac_file"':,' < "$tmp"/out`
-      { echo "$as_me:4708: WARNING: Some variables may not be substituted:
+      { echo "$as_me:4712: WARNING: Some variables may not be substituted:
 $ac_seen" >&5
 echo "$as_me: WARNING: Some variables may not be substituted:
 $ac_seen" >&2;}
