snapshot of project "ded", label t20100323

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 # From configure.in Revision: 12.6 .
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Autoconf 2.52.20081225.
+# Generated by Autoconf 2.52.20100320.
 #
 # Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
 # Free Software Foundation, Inc.
@@ -703,7 +703,7 @@ This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
 It was created by $as_me, which was
-generated by GNU Autoconf 2.52.20081225.  Invocation command line was
+generated by GNU Autoconf 2.52.20100320.  Invocation command line was
 
   $ $0 $@
 
@@ -2207,28 +2207,25 @@ else
 
 	cf_cv_tdlib_devel=no
 
-	test -d ../td_lib &&
-	test -d ../td_lib/include &&
-	test -f ../td_lib/include/td_config.h &&
-	test -d ../td_lib/lib &&
-	test -f ../td_lib/lib/${LIB_PREFIX}td.a &&
-	cf_cv_tdlib_devel=yes
-
-	if test "$cf_cv_tdlib_devel" = yes ; then
-		cf_save_CFLAGS="$CFLAGS"
-		cf_save_LIBS="$LIBS"
-		CFLAGS="$CFLAGS -I`cd ../td_lib/include;pwd`"
-		LIBS="-L`cd ../td_lib/lib;pwd` $LIBS"
-		TD_LIB_rules=`cd ../td_lib/support;pwd`
-	fi
+	for cf_path in . ..
+	do
+		test -d $cf_path/td_lib &&
+		test -d $cf_path/td_lib/include &&
+		test -f $cf_path/td_lib/include/td_config.h &&
+		test -d $cf_path/td_lib/lib &&
+		test -f $cf_path/td_lib/lib/${LIB_PREFIX}td.a &&
+		cf_cv_tdlib_devel=`CDPATH=; export CDPATH; cd $cf_path/td_lib;pwd` &&
+		break
+	done
 
 fi
 
-echo "$as_me:2227: result: $cf_cv_tdlib_devel" >&5
+echo "$as_me:2223: result: $cf_cv_tdlib_devel" >&5
 echo "${ECHO_T}$cf_cv_tdlib_devel" >&6
 
 if test "$cf_cv_tdlib_devel" = no ; then
 
+cf_search=
 cf_header_path_list=""
 if test -n "${CFLAGS}${CPPFLAGS}" ; then
 	for cf_header_path in $CPPFLAGS $CFLAGS
@@ -2335,13 +2332,13 @@ cf_search="$cf_header_path_list $cf_search"
 
 	eval 'cf_cv_have_lib_'td'=no'
 	cf_libdir=""
-	echo "$as_me:2338: checking for doalloc" >&5
+	echo "$as_me:2335: checking for doalloc" >&5
 echo $ECHO_N "checking for doalloc... $ECHO_C" >&6
 if test "${ac_cv_func_doalloc+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 2344 "configure"
+#line 2341 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char doalloc (); below.  */
@@ -2372,16 +2369,16 @@ f = doalloc;
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:2375: \"$ac_link\"") >&5
+if { (eval echo "$as_me:2372: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:2378: \$? = $ac_status" >&5
+  echo "$as_me:2375: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:2381: \"$ac_try\"") >&5
+  { (eval echo "$as_me:2378: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:2384: \$? = $ac_status" >&5
+  echo "$as_me:2381: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_func_doalloc=yes
 else
@@ -2391,18 +2388,18 @@ ac_cv_func_doalloc=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:2394: result: $ac_cv_func_doalloc" >&5
+echo "$as_me:2391: result: $ac_cv_func_doalloc" >&5
 echo "${ECHO_T}$ac_cv_func_doalloc" >&6
 if test $ac_cv_func_doalloc = yes; then
   eval 'cf_cv_have_lib_'td'=yes'
 else
 
 		cf_save_LIBS="$LIBS"
-		echo "$as_me:2401: checking for doalloc in -ltd" >&5
+		echo "$as_me:2398: checking for doalloc in -ltd" >&5
 echo $ECHO_N "checking for doalloc in -ltd... $ECHO_C" >&6
 		LIBS="-ltd $LIBS"
 		cat >conftest.$ac_ext <<_ACEOF
-#line 2405 "configure"
+#line 2402 "configure"
 #include "confdefs.h"
 
 #define TESTING_CONFIG_H
@@ -2417,25 +2414,25 @@ main ()
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:2420: \"$ac_link\"") >&5
+if { (eval echo "$as_me:2417: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:2423: \$? = $ac_status" >&5
+  echo "$as_me:2420: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:2426: \"$ac_try\"") >&5
+  { (eval echo "$as_me:2423: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:2429: \$? = $ac_status" >&5
+  echo "$as_me:2426: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  echo "$as_me:2431: result: yes" >&5
+  echo "$as_me:2428: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 			 eval 'cf_cv_have_lib_'td'=yes'
 
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-echo "$as_me:2438: result: no" >&5
+echo "$as_me:2435: result: no" >&5
 echo "${ECHO_T}no" >&6
 
 cf_library_path_list=""
@@ -2524,11 +2521,11 @@ cf_search="$cf_library_path_list $cf_search"
 
 			for cf_libdir in $cf_search
 			do
-				echo "$as_me:2527: checking for -ltd in $cf_libdir" >&5
+				echo "$as_me:2524: checking for -ltd in $cf_libdir" >&5
 echo $ECHO_N "checking for -ltd in $cf_libdir... $ECHO_C" >&6
 				LIBS="-L$cf_libdir -ltd $cf_save_LIBS"
 				cat >conftest.$ac_ext <<_ACEOF
-#line 2531 "configure"
+#line 2528 "configure"
 #include "confdefs.h"
 
 #define TESTING_CONFIG_H
@@ -2543,25 +2540,25 @@ main ()
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:2546: \"$ac_link\"") >&5
+if { (eval echo "$as_me:2543: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:2549: \$? = $ac_status" >&5
+  echo "$as_me:2546: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:2552: \"$ac_try\"") >&5
+  { (eval echo "$as_me:2549: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:2555: \$? = $ac_status" >&5
+  echo "$as_me:2552: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  echo "$as_me:2557: result: yes" >&5
+  echo "$as_me:2554: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 			 		 eval 'cf_cv_have_lib_'td'=yes'
 					 break
 else
   echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
-echo "$as_me:2564: result: no" >&5
+echo "$as_me:2561: result: no" >&5
 echo "${ECHO_T}no" >&6
 					 LIBS="$cf_save_LIBS"
 fi
@@ -2576,7 +2573,7 @@ fi
 eval 'cf_found_library=$cf_cv_have_lib_'td
 
 if test $cf_found_library = no ; then
-	{ { echo "$as_me:2579: error: Cannot link td library" >&5
+	{ { echo "$as_me:2576: error: Cannot link td library" >&5
 echo "$as_me: error: Cannot link td library" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -2676,14 +2673,18 @@ cf_search="$cf_library_path_list $cf_search"
 				break
 			fi
 		done
-		test $cf_td_lib_rules = no && { { echo "$as_me:2679: error: Cannot find td_lib.mk" >&5
+		test $cf_td_lib_rules = no && { { echo "$as_me:2676: error: Cannot find td_lib.mk" >&5
 echo "$as_me: error: Cannot find td_lib.mk" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 	TD_LIB_rules=$cf_libdir
+else
+	CPPFLAGS="$CPPFLAGS -I$cf_cv_tdlib_devel/include $CPPFLAGS"
+	LIBS="-L$cf_cv_tdlib_devel/lib $LIBS"
+	TD_LIB_rules=$cf_cv_tdlib_devel/support
 fi
 
-echo "$as_me:2686: checking if ${MAKE-make} program knows about archives" >&5
+echo "$as_me:2687: checking if ${MAKE-make} program knows about archives" >&5
 echo $ECHO_N "checking if ${MAKE-make} program knows about archives... $ECHO_C" >&6
 if test "${cf_cv_ar_rules+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -2736,7 +2737,7 @@ if ( cd $cf_dir && ${MAKE-make} 2>&5 >&5 && test -f conf.a )
 then
 	cf_cv_ar_rules=no
 else
-	{ { echo "$as_me:2739: error: I do not know how to construct a library" >&5
+	{ { echo "$as_me:2740: error: I do not know how to construct a library" >&5
 echo "$as_me: error: I do not know how to construct a library" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -2745,10 +2746,10 @@ rm -rf $cf_dir
 
 fi
 
-echo "$as_me:2748: result: $cf_cv_ar_rules" >&5
+echo "$as_me:2749: result: $cf_cv_ar_rules" >&5
 echo "${ECHO_T}$cf_cv_ar_rules" >&6
 
-echo "$as_me:2751: checking for style of include in makefiles" >&5
+echo "$as_me:2752: checking for style of include in makefiles" >&5
 echo $ECHO_N "checking for style of include in makefiles... $ECHO_C" >&6
 
 make_include_left=""
@@ -2788,7 +2789,7 @@ done
 rm -rf $cf_inc $cf_dir
 
 if test -z "$make_include_left" ; then
-	{ { echo "$as_me:2791: error: Your $ac_make program does not support includes" >&5
+	{ { echo "$as_me:2792: error: Your $ac_make program does not support includes" >&5
 echo "$as_me: error: Your $ac_make program does not support includes" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -2797,7 +2798,7 @@ if test ".$make_include_quote" != .unknown ; then
 	make_include_right="$make_include_quote"
 fi
 
-echo "$as_me:2800: result: ${make_include_left}file${make_include_right}" >&5
+echo "$as_me:2801: result: ${make_include_left}file${make_include_right}" >&5
 echo "${ECHO_T}${make_include_left}file${make_include_right}" >&6
 
 ### Compiler characteristics
@@ -2921,7 +2922,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:2924: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:2925: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -3048,7 +3049,7 @@ EOF
 cat >>$CONFIG_STATUS <<EOF
 ac_cs_version="\\
 config.status
-configured by $0, generated by GNU Autoconf 2.52.20081225,
+configured by $0, generated by GNU Autoconf 2.52.20100320,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
 Copyright 1992, 1993, 1994, 1995, 1996, 1998, 1999, 2000, 2001
@@ -3092,7 +3093,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:3095: error: ambiguous option: $1
+    { { echo "$as_me:3096: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3111,7 +3112,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:3114: error: unrecognized option: $1
+  -*) { { echo "$as_me:3115: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3130,7 +3131,7 @@ cat >&5 << _ACEOF
 ## Running config.status.  ##
 ## ----------------------- ##
 
-This file was extended by $as_me 2.52.20081225, executed with
+This file was extended by $as_me 2.52.20100320, executed with
   CONFIG_FILES    = $CONFIG_FILES
   CONFIG_HEADERS  = $CONFIG_HEADERS
   CONFIG_LINKS    = $CONFIG_LINKS
@@ -3163,7 +3164,7 @@ do
   "test/makefile" ) CONFIG_FILES="$CONFIG_FILES test/makefile" ;;
   "user/makefile" ) CONFIG_FILES="$CONFIG_FILES user/makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
-  *) { { echo "$as_me:3166: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3167: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3390,7 +3391,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3393: creating $ac_file" >&5
+    { echo "$as_me:3394: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3408,7 +3409,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3411: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3412: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3421,7 +3422,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3424: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3425: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
